# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='collection',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldatabaseconnection',
            name='collection',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
