# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_auto_20160726_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_manager.DatabaseType'),
        ),
    ]
