# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_databasequerie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabaseQuerie',
            new_name='DatabaseQuery',
        ),
        migrations.RenameField(
            model_name='databasequery',
            old_name='querie',
            new_name='query',
        ),
    ]
