# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database_manager', '0003_auto_20160718_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
