# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0005_historicaldatabaseconnection_historicaldatabasequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=15)),
            ],
        ),
    ]
