# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0006_databasetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database_manager.DatabaseType'),
        ),
        migrations.AddField(
            model_name='historicaldatabaseconnection',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database_manager.DatabaseType'),
        ),
    ]
